name: Make Patch

on:
  pull_request:
    branches:
      - master

permissions:
  issues: write

jobs:
  make_patch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create diff
        run: |
          mkdir -p .github/patch_data
          git fetch origin
          git diff origin/${{ github.base_ref }}  -- . ':!.github' ':!patch' > .github/patch_data/unified_diff.patch
          cp patch/*.qml patch/*.png patch/*.js patch/*.svg patch/*.qm .github/patch_data |:
        
      - name: Upload build result
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.head_ref }}
          path: .github/patch_data

      - name: View context attributes
        uses: actions/github-script@v7
        with:
          script: console.log(context)

      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Hello @${{ github.event.pull_request.user.login }}\nYour patch is ready!\n\n[Download link](${{ steps.artifact-upload-step.outputs.artifact-url }})'
            })
